name: Build
on: push

env:
  STUNNEL_VERSION: 5.74

jobs:
  build-x86_64:
    env:
      DEST_ARCH: x86_64
    runs-on: ubuntu-latest
    container:
      image: docker://alpine:latest
    steps:
      - name: Checkout repository
        uses: taiki-e/checkout-action@v1
      - name: Install dependencies and build stunnel
        run: ./build.sh

  build-i686:
    env:
      DEST_ARCH: i686
    runs-on: ubuntu-latest
    container:
      image: docker://i386/alpine:latest
    steps:
      - name: Checkout repository
        uses: taiki-e/checkout-action@v1
      - name: Install dependencies and build stunnel
        run: ./build.sh

  release:
    needs: [build-x86_64, build-i686]
    runs-on: ubuntu-latest
    steps:
      - name: Upload binary to Releases
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          fail_on_unmatched_files: true
          files: dist/*
